[env:skr_pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0m
monitor_speed = 115200
lib_deps =
	teemuatlut/TMCStepper@^0.7.3
	gin66/FastAccelStepper@^0.31.0
build_flags = -Wall -D__FREERTOS=1
